version: "3"

services:

  nginx:
    hostname: nginxcompose
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    volumes:
        - ./docker/certbot/www:/usr/share/nginx/html
        - ./docker/nginx:/etc/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - projeto_php
networks:
  projeto_php:
    driver: bridge
